export { default as CrossCircle } from './svg/CrossCircle.svg'
export { default as Add } from './svg/Add.svg'
export { default as PlusSmall } from './svg/PlusSmall.svg'
export { default as Copy } from './svg/Copy.svg'
export { default as Facebook } from './svg/Facebook.svg'
export { default as Twitter } from './svg/Twitter.svg'
export { default as Whatsapp } from './svg/Whatsapp.svg'
