'use client'

import MockRequirementsForm from '@/components/MockRequirementsForm/MockRequirementsForm'
import { encodeObject } from '@/lib'
import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Mocker v1</h1>

      <div style={{ display: 'flex', gap: 30 }}>
        <div>
          <h2>Form</h2>
          <MockRequirementsForm
            onSubmit={({ fields }) => {
              Router.push({
                pathname: '/preview',
                query: { fields: encodeObject(fields) }
              })
            }}
          />
        </div>
      </div>
    </>
  )
}

export default Home
