import MockRequirementsForm from '@/components/MockRequirementsForm/MockRequirementsForm'
import { encodeObject } from '@/lib'
import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Mocker v1</h1>

      <MockRequirementsForm
        onSubmit={(data) =>
          Router.push({
            pathname: '/preview',
            query: { fields: encodeObject(data.fields) }
          })
        }
      />
    </>
  )
}

export default Home
