import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form>
        <table>
          <tr>
            <th>Name</th>
            <th>Type</th>
          </tr>
          <tr>
            <td>
              <input type="text" name="field_name" />
            </td>
            <td>
              <select>
                {options.map((value) => (
                  <option key={value}>{value}</option>
                ))}
              </select>
            </td>
          </tr>
        </table>
      </form>
    </>
  )
}

const options = ['email', 'id', 'first anme']

export default Home
