import MockRequirementsForm from '@/components/MockRequirementsForm/MockRequirementsForm'
import PreviewUrl from '@/components/PreviewUrl/PreviewUrl'
import { encodeObject } from '@/lib'
import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Mocker v1</h1>

      <div style={{ display: 'flex', gap: 30 }}>
        <div>
          <h2>Form</h2>
          <MockRequirementsForm
            onSubmit={
              (data) => console.log({ data })
              // Router.push({
              //   pathname: '/preview',
              //   query: { fields: encodeObject(data.fields) }
              // })
            }
          />
        </div>
        <div>
          <h2>Preview</h2>
          <PreviewUrl />
        </div>
      </div>
    </>
  )
}

export default Home
